---
# This playbook stops all running Apache httpd and Tomcat server instances.

- hosts: tomcat-servers
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - backup-tomcat
    - delete-tomcat
