---
# This playbook a) Installs and deploys Apache httpd proxy/web server and b) Installs and deploys multiple instances of Apache Tomcat 8 Servers on multiple hosts.
# The Tomcat instances are front ended by a proxy/lb server (Apache httpd)

#- hosts: web-servers
#  become: yes
#  become_method: sudo

#  roles:
#    - selinux
#    - apacheHttpd

# parameters
# catalina_version: 8.5.37
# backup_catalina_version: 8.5.35
# delete_catalina_version: 8.5.35

- hosts: tomcat-servers
  become: yes
  become_method: sudo

  roles:
#    - selinux
    - backup-tomcat
    - delete-tomcat
    - tomcat-try
