---
# Stop all Apache Tomcat instances and delete the install directory.

- name: Start all tomcat instances
  command: "/home/tomcat/te/tomcat8/instances/{{ item.value.name }}/bin/startup.sh"
#  shell: /home/tomcat/te/tomcat8/instances/{{ item.value.name }}/bin/startup.sh
#  args:
#    executable: /bin/bash
  with_dict: "{{ nodes }}"
  register : result
- debug: var=result


#- name: Delete the Tomcat/Catalina Home and all Base directories underneath
#  file:
#    path: /home/tomcat/te
#    state: absent
