---
# - name: restart tomcat
#   shell: /home/tomcat/te/tomcat8/instances/{{ item.value.name }}/bin/startup.sh
#   args:
#     executable: /bin/bash
#   with_dict: "{{ nodes }}"
#   become: yes
#   become_user: tomcat
#   become_method: sudo

  - name: restart tomcat
    command: nohup sh startup.sh
    args:
      chdir: /home/tomcat/te/tomcat8/instances/{{ item.value.name }}/bin/
    with_dict: "{{ nodes }}"
    become: yes
    become_user: tomcat
    become_method: sudo
