---
# Stop all Apache Tomcat instances and delete the install directory.

- name: Stop all tomcat instances
  shell: /home/tomcat/te/tomcat8/instances/{{ item.value.name }}/bin/shutdown.sh
  args:
    executable: /bin/bash
  with_dict: "{{ nodes }}"
  ignore_errors: yes

- name: Delete the Tomcat/Catalina Home and all Base directories underneath
 file:
   path: /home/tomcat/te
   state: absent
