---
# Stop all Apache Tomcat instances, backup and delete the install directory.

- name: Stop all tomcat instances
  shell: "{{catalina_base}}/instances/{{ item.value.name }}/bin/shutdown.sh"
  args:
    executable: /bin/bash
  with_dict: "{{ nodes }}"
  ignore_errors: yes

- name: Delete the Tomcat/Catalina Home and all Base directories underneath
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{catalina_base}}/instances"
    - "{{catalina_base}}/apache-tomcat-{{delete_catalina_version}}"
  tags:
    - deleteBaseInstances
